### ISSUE TITLE
Error in default emtpy project

### ISSUE THREAD

**Issue by fr0gs** [rcolinray/generator-phaser-typescript#7]
I run into this error when I create a new **phaser-typescript** project with yeoman:

`
>> app/vendor/phaser-official/typescript/pixi.d.ts(605,18): error TS2415: Class 'Graphics' incorrectly extends base class 'DisplayObjectContainer'.
>>   Types of property 'generateTexture' are incompatible.
>>     Type '(resolution?: number, scaleMode?: number) => Texture' is not assignable to type '(resolution?: number, scaleMode?: number, renderer?: PixiRenderer) => RenderTexture'.
>>       Type 'Texture' is not assignable to type 'RenderTexture'.
>>         Property 'renderer' is missing in type 'Texture'.
`

**Comment by rcolinray** [comment]
This is a known issue with Phaser: https://github.com/photonstorm/phaser/issues/2492. Closing

Thanks for using the generator!
