### ISSUE TITLE
Cannot install generator

### ISSUE THREAD

**Issue by smatthews1999** [rcolinray/generator-phaser-typescript#8]
I am getting an unmet dependency, but I have just installed the latest YO.
Any ideas?
![image](https://cloud.githubusercontent.com/assets/562964/22488571/db52e3c4-e7e0-11e6-8b9c-12c8fd310b28.png)

**Comment by smatthews1999** [comment]
Seems to be a common problem with Yoeman

**Comment by rcolinray** [comment]
Were you able to solve the problem?

**Comment by smatthews1999** [comment]
Sorry I was not.  It seems to be a problem with yeoman generators.
